const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0)),pct=n=>`${Math.round(Number(n||0))}%`;
let current;const actor=()=>localStorage.getItem('money_moves_actor')||'Household member';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function initials(name){return String(name||'MM').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'MM'}
function logo(item){return item?.logoUrl?`<img class="merchant-logo" src="${esc(item.logoUrl)}" alt="" referrerpolicy="no-referrer" onerror="this.outerHTML='<span class=&quot;merchant-fallback&quot;>${esc(initials(item.merchant))}</span>'">`:`<span class="merchant-fallback">${esc(initials(item?.merchant))}</span>`}
function setStatus(message,isError=false){const el=$('#status');if(!el)return;el.textContent=message||'';el.classList.toggle('error',!!isError)}
async function api(url,opts={}){const r=await fetch(url,{cache:'no-store',...opts});const d=await r.json().catch(()=>({}));if(r.status===401){showLogin();throw Error('Household access key required')}if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
function showLogin(){$('#authGate').classList.remove('hidden')}
async function authInit(){const a=await fetch('/api/auth-status',{cache:'no-store'}).then(r=>r.json());if(a.required&&!a.authenticated){showLogin();return false}return true}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{$('#loginError').textContent='';const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:$('#accessKey').value})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Could not unlock');$('#authGate').classList.add('hidden');await load()}catch(err){$('#loginError').textContent=err.message}};
function setTab(name){$$('.tab-screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));history.replaceState(null,'',`#${name}`);window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(btn=>btn.onclick=()=>setTab(btn.dataset.tab));$$('[data-jump]').forEach(btn=>btn.onclick=()=>setTab(btn.dataset.jump));
async function load(){current=await api('/api/state');render()}
function row(label,value,sub=''){return `<div><span>${esc(label)}${sub?`<small class="row-sub">${esc(sub)}</small>`:''}</span><b>${value}</b></div>`}
function merchantRow(x,sub,amount,withSelect=false){const categories=[['discretionary','Discretionary'],['groceries','Groceries'],['gas','Gas / fuel'],['utilities','Utilities'],['bills','Bills'],['subscription','Subscription'],['essential','Other essential'],['ignore','Ignore / transfer']];return `<div class="merchant-row">${logo(x)}<span class="merchant-copy"><b>${esc(x.merchant)}</b><small>${esc(sub)}</small></span><span class="merchant-amount">${money(amount)}</span>${withSelect?`<select data-tx="${esc(x.id)}" aria-label="Correct category"><option value="">Change category…</option>${categories.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select>`:''}</div>`}
function render(){const s=current.state,r=current.rules,p=current.plan,b=current.bank,sp=current.spend,bu=current.budget;
$('#brief').textContent=current.brief;$('#heroMove').textContent=p.message;
let mode='LIVE';if(current.incomeEvents.payday.detected)mode='PAYDAY MODE';else if(current.incomeEvents.firstOfMonth.detected)mode='1ST-OF-MONTH MODE';$('#modeBadge').textContent=mode;
$('#moves').innerHTML=`<article><small>15TH RESERVE</small><strong>${money(p.toReserveNow)}</strong><span>${p.toReserveNow>0?'Move now':'No transfer needed now'}</span>${p.toReserveNow>0?'<button class="tiny done" data-move="reserve">Mark done</button>':''}</article><article><small>LONG-TERM SAVINGS</small><strong>${money(p.toSavingsNow)}</strong><span>${p.toSavingsNow>0?'True excess available now':'Reserve + floor protected first'}</span>${p.toSavingsNow>0?'<button class="tiny done" data-move="savings">Mark done</button>':''}</article><article><small>NEXT PAYCHECK</small><strong>${money(p.nextPaycheck)}</strong><span>Projected savings ${money(p.projected.toSavings)}</span></article>`;
$('#safe').innerHTML=`<div class="big-number">${money(p.safeToSpendNow)}</div><p>Cash above the ${money(r.checking_floor)} checking floor after required bill holdbacks.</p><div class="meter"><span style="width:${Math.min(100,sp.discretionary.spendProgress)}%"></span></div><p><b>${money(sp.discretionary.remaining)}</b> discretionary left · ${money(sp.discretionary.dailyAllowance)}/day · pace ${sp.discretionary.status.replace('_',' ')}</p>`;
const daily=`<article><small>TODAY</small><strong>${money(sp.today.total)}</strong><span>${money(sp.today.discretionary)} discretionary</span></article><article><small>YESTERDAY</small><strong>${money(sp.yesterday.total)}</strong><span>${money(sp.yesterday.discretionary)} discretionary</span></article><article><small>MONTH TO DATE</small><strong>${money(sp.monthToDate.total)}</strong><span>${sp.monthToDate.transactionCount} purchases</span></article><article><small>DISCRETIONARY</small><strong>${money(sp.monthToDate.discretionary)}</strong><span>of ${money(r.discretionary_cap)}</span></article>`;$('#daily').innerHTML=daily;$('#spendSummaryMirror').innerHTML=daily;
$('#topTx').innerHTML=sp.topTransactions.length?sp.topTransactions.map(t=>merchantRow(t,`${t.date} · ${t.category}`,t.amount,true)).join(''):'<p>No posted spending yet this month.</p>';
const rw=current.runway;$('#runway').innerHTML=`<div class="feature-head"><div><small>NEXT CHECKPOINT</small><div class="big-number small">${esc(rw.checkpoint)}</div></div><span class="status ${rw.status}">${rw.status.replace('_',' ')}</span></div><div class="progress"><span style="width:${Math.min(100,rw.required?rw.funded/rw.required*100:100)}%"></span></div><p>${money(rw.funded)} funded of ${money(rw.required)} · gap ${money(rw.gap)} · due ${esc(rw.nextDue)}</p><p><b>1st-of-month bills:</b> ${rw.firstBillsConfirmed?'confirmed paid':'not yet confirmed'}</p><button id="checkpoint" class="tiny secondary">${rw.firstBillsConfirmed?'Mark unconfirmed':'Mark 1st bills paid'}</button>`;
$('#monthly').innerHTML=`<article><small>SPENDABLE INCOME</small><strong>${money(bu.spendableIncome)}</strong><span>Monthly plan</span></article><article><small>EXPENSES</small><strong>${money(bu.monthlyExpenses)}</strong><span>Planned</span></article><article><small>OPERATING SURPLUS</small><strong>${money(bu.operatingSurplus)}</strong><span>Spendable minus expenses</span></article><article><small>SAVINGS TARGET</small><strong>${money(bu.totalSavingsTarget)}</strong><span>Surplus + buffer</span></article>`;
const sc=current.scorecard,progress=sc.target?Math.min(100,sc.actual/sc.target*100):0;$('#scorecard').innerHTML=`<div class="feature-head"><div><small>OBSERVED SAVINGS INFLOW</small><div class="big-number small">${money(sc.actual)}</div></div><b>${pct(progress)}</b></div><div class="progress"><span style="width:${progress}%"></span></div><p>Monthly target ${money(sc.target)} · remaining ${money(Math.max(0,sc.gap))}.</p>`;
const w=current.weekly;$('#weekly').innerHTML=`<div class="mini-grid"><div><small>SPENT</small><b>${money(w.spent)}</b></div><div><small>DISCRETIONARY</small><b>${money(w.discretionary)}</b></div><div><small>INCOME</small><b>${money(w.income)}</b></div></div><p>${esc(w.from)} through ${esc(w.to)} · ${w.transactions} purchases</p>`;
$('#subscriptions').innerHTML=current.subscriptions.length?current.subscriptions.map(x=>merchantRow(x,`~every ${x.frequencyDays} days · next ${x.nextExpected}${x.priceChange?` · ${x.priceChange>0?'up':'down'} ${money(Math.abs(x.priceChange))}`:''}`,x.amount)).join(''):'<p>No recurring monthly charges confidently detected yet.</p>';
$('#alertsList').innerHTML=current.alerts.length?current.alerts.map(x=>merchantRow(x,`${x.date} · ${x.reason}`,x.amount)).join(''):'<p>No unusual posted purchases detected this month.</p>';
$('#forecast').innerHTML=current.forecast.events.length?current.forecast.events.map(e=>`<div class="timeline-row"><span class="dot ${e.type}"></span><span><b>${esc(e.label)}</b><small>${esc(e.date)} · projected liquid ${money(e.projectedLiquid)}</small></span><strong class="${e.amount<0?'negative':'positive'}">${e.amount<0?'−':'+'}${money(Math.abs(e.amount))}</strong></div>`).join(''):'<p>No forecast events.</p>';
$('#routing').innerHTML=current.routing.length?`<p>Current safe sweep of <b>${money(p.toSavingsNow)}</b> would route:</p>${current.routing.map(x=>row(`${x.name} · ${x.percent}%`,money(x.amount))).join('')}`:'<p>No savings sweep available right now.</p>';
const routeMap=new Map(current.savingsRoutes.map(x=>[x.name,Number(x.percent)]));for(const name of ['Long-term savings','Car payoff','Brokerage'])if(!routeMap.has(name))routeMap.set(name,0);$('#routeForm').innerHTML=`<div class="route-inputs">${[...routeMap].map(([name,percent])=>`<label><span>${esc(name)}</span><input type="number" min="0" max="100" step="1" value="${percent}" data-route="${esc(name)}"></label>`).join('')}</div><button class="tiny" type="submit">Save routing</button>`;
$('#accounts').innerHTML=row('Checking',money(s.checking))+row('15th reserve',money(s.reserve))+row('Long-term savings',money(s.savings))+row('Discretionary this month',`${money(sp.monthToDate.discretionary)} / ${money(r.discretionary_cap)}`);
$('#banks').innerHTML=b.items.length?b.items.map(x=>row(x.institution_name||'Connected bank',x.sync_error?'Needs attention':'Connected',x.last_synced_at?`Last sync ${new Date(x.last_synced_at).toLocaleString()}`:'')).join(''):`<p>${b.configured?'No bank connected yet.':'Plaid credentials are not configured.'}</p>`;
$('#activity').innerHTML=current.activity.length?current.activity.map(x=>row(x.detail||x.type,esc(x.actor),new Date(x.created_at).toLocaleString())).join(''):'<p>No household activity yet.</p>';
$('#rules').innerHTML=row('Checking minimum',money(r.checking_floor))+row('15th reserve target',money(r.reserve_target))+row('Discretionary cap',money(r.discretionary_cap))+row('Budget-eligible VA',money(r.budget_eligible_va));
$('#securityBanner').classList.toggle('hidden',current.security.configured);if(!current.security.configured)$('#securityBanner').innerHTML='<b>Private-beta protection is not enabled.</b> Add MONEY_MOVES_ACCESS_KEY in Railway before sharing this URL.';$('#member').textContent=initials(actor());bindDynamic();}
function bindDynamic(){const cp=$('#checkpoint');if(cp)cp.onclick=async()=>{try{current=await api('/api/checkpoint',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({checkpoint:'first_bills',completed:!current.runway.firstBillsConfirmed,actor:actor()})});render();setStatus(current.runway.firstBillsConfirmed?'1st-of-month bills confirmed paid.':'1st-of-month bills marked unconfirmed.')}catch(e){setStatus(e.message,true)}};$$('.done').forEach(btn=>btn.onclick=async()=>{const amount=btn.dataset.move==='reserve'?current.plan.toReserveNow:current.plan.toSavingsNow,detail=btn.dataset.move==='reserve'?`Completed ${money(amount)} move to 15th reserve`:`Completed ${money(amount)} sweep to long-term savings`;await api('/api/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'move_completed',detail,actor:actor()})});setStatus('Move marked complete.');await load()});$$('select[data-tx]').forEach(sel=>sel.onchange=async()=>{if(!sel.value)return;try{setStatus('Learning merchant rule…');current=await api('/api/merchant-rule',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({transactionId:sel.dataset.tx,category:sel.value,actor:actor()})});render();setStatus('Merchant rule saved and reports recalculated.')}catch(e){setStatus(e.message,true)}})}
$('#routeForm').onsubmit=async e=>{e.preventDefault();const map=new Map();$$('[data-route]').forEach(i=>map.set(i.dataset.route,Number(i.value||0)));const routes=[...map.entries()].filter(([,percent])=>percent>0).map(([name,percent])=>({name,percent}));try{current=await api('/api/savings-routes',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({routes,actor:actor()})});render();setStatus('Savings routing updated.')}catch(err){setStatus(err.message,true)}};
$('#member').onclick=()=>{const name=prompt('Name shown in household activity',actor());if(name&&name.trim()){localStorage.setItem('money_moves_actor',name.trim().slice(0,40));$('#member').textContent=initials(actor());setStatus(`Activity will be recorded as ${actor()}.`)}};
function waitForPlaid(timeoutMs=5000){return new Promise((resolve,reject)=>{if(window.Plaid)return resolve(window.Plaid);const started=Date.now(),timer=setInterval(()=>{if(window.Plaid){clearInterval(timer);resolve(window.Plaid)}else if(Date.now()-started>=timeoutMs){clearInterval(timer);reject(Error('Plaid Link did not load. Refresh and check content blockers.'))}},100)})}
async function connectBank(){const btn=$('#connect');try{if(btn)btn.disabled=true;setStatus('Opening secure bank connection…');const plaid=await waitForPlaid(),d=await api('/api/bank/link-token',{method:'POST'}),handler=plaid.create({token:d.linkToken,onSuccess:async publicToken=>{try{setStatus('Finishing bank connection…');await api('/api/bank/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publicToken})});await load();setStatus('Bank connected successfully.')}catch(e){setStatus(e.message,true)}finally{if(btn)btn.disabled=false}},onExit:err=>{if(btn)btn.disabled=false;setStatus(err?(err.display_message||err.error_message||'Bank connection closed with an error.'):'Bank connection closed.',!!err)}});handler.open()}catch(e){if(btn)btn.disabled=false;setStatus(e.message,true)}}
async function syncBank(){try{setStatus('Refreshing balances, transactions and insights…');await api('/api/bank/sync',{method:'POST'});await load();setStatus('Bank data and Money Moves refreshed.')}catch(e){setStatus(e.message,true)}}
$('#connect').onclick=connectBank;$('#connectSettings').onclick=connectBank;$('#sync').onclick=syncBank;$('#syncSettings').onclick=syncBank;
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
$('#alerts').onclick=async()=>{try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('Push notifications are not supported on this browser.');const cfg=await api('/api/push/public-key');if(!cfg.configured)throw Error('Push is not configured on the server yet.');const perm=await Notification.requestPermission();if(perm!=='granted')throw Error('Notification permission was not granted.');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(cfg.publicKey)});await api('/api/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(sub)});setStatus('Daily, weekly, payday and spending alerts enabled.')}catch(e){setStatus(e.message,true)}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(console.error);const startTab=location.hash.replace('#','');if(['home','spend','plan','accounts','settings'].includes(startTab))setTab(startTab);authInit().then(ok=>{if(ok)load().catch(e=>setStatus(e.message,true))}).catch(e=>setStatus(e.message,true));
