(()=>{
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
let billState=null,editingId=null;
async function api(url,opts={}){const r=await fetch(url,{cache:'no-store',...opts}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
function statusLabel(b){if(b.status==='paid_auto')return '<span class="bill-status paid">✓ Auto paid</span>';if(b.status==='paid_manual')return '<span class="bill-status manual">✓ Manual</span>';if(b.status==='overdue')return '<span class="bill-status overdue">Overdue</span>';if(b.status==='due_soon')return '<span class="bill-status due">Due soon</span>';return '<span class="bill-status upcoming">Upcoming</span>'}
function summary(){if(!billState)return'';const f=billState.summary.first,x=billState.summary.fifteenth;return `<div class="bill-summary-grid"><div><small>1ST / CHECKING</small><b>${money(f.remaining)}</b><span>${money(f.paid)} paid of ${money(f.planned)}</span></div><div><small>15TH RESERVE</small><b>${money(x.remaining)}</b><span>${money(x.paid)} paid of ${money(x.planned)}</span></div></div>`}
function row(b){const match=b.matchedTransaction?`${b.matchedTransaction.merchant} · ${money(b.matchedTransaction.amount)} · ${b.matchedTransaction.date}`:`Expected ${money(b.amount)} · due day ${b.dueDay}`;return `<article class="planned-bill-row"><div class="bill-main"><span class="bill-icon">${b.bucket==='fifteenth'?'15':'1'}</span><div><b>${esc(b.name)}</b><small>${esc(match)}</small><small>Match: ${esc(b.merchantMatch||b.name)}</small></div></div><div class="bill-side">${statusLabel(b)}<b>${money(b.amount)}</b></div><div class="bill-actions"><button data-bill-edit="${b.id}">Edit</button>${b.status.startsWith('paid_')?`<button data-bill-manual="${b.id}" data-paid="false">Mark unpaid</button>`:`<button data-bill-manual="${b.id}" data-paid="true">Mark paid</button>`}<button class="danger" data-bill-delete="${b.id}">Delete</button></div></article>`}
function form(b={}){return `<form id="billForm" class="bill-form"><div class="bill-form-head"><b>${b.id?'Edit bill':'Add monthly bill'}</b><button type="button" id="cancelBill">×</button></div><label>Bill name<input id="billName" value="${esc(b.name||'')}" placeholder="Mortgage, Verizon, Netflix…" required></label><label>Merchant / transaction match<input id="billMatch" value="${esc(b.merchantMatch||'')}" placeholder="Text that appears in the bank transaction"></label><div class="bill-form-grid"><label>Expected amount<input id="billAmount" type="number" min="0" step="0.01" value="${b.amount??''}" required></label><label>Due day<input id="billDue" type="number" min="1" max="31" value="${b.dueDay??1}" required></label></div><label>Fund from<select id="billBucket"><option value="first" ${b.bucket==='first'?'selected':''}>1st / Checking</option><option value="fifteenth" ${b.bucket==='fifteenth'?'selected':''}>15th Reserve</option></select></label><button class="primary-small" type="submit">${b.id?'Save bill':'Add bill'}</button><p class="bill-help">Money Moves will match posted bank transactions automatically. Manual paid/unpaid stays available as a fallback.</p></form>`}
function render(){const host=$('#billPlanner'),sum=$('#billSummary');if(!host||!sum||!billState)return;sum.innerHTML=summary();host.innerHTML=(editingId!==null?form(billState.bills.find(x=>x.id===editingId)||{}):'')+(billState.bills.length?billState.bills.map(row).join(''):'<div class="bill-empty"><b>No planned bills yet.</b><span>Add your recurring bills once. Money Moves will then reconcile them against posted transactions every month.</span></div>');bind()}
function bind(){const formEl=$('#billForm');if(formEl){$('#cancelBill').onclick=()=>{editingId=null;render()};formEl.onsubmit=async e=>{e.preventDefault();const body={name:$('#billName').value.trim(),merchantMatch:$('#billMatch').value.trim(),amount:Number($('#billAmount').value),dueDay:Number($('#billDue').value),bucket:$('#billBucket').value,actor:localStorage.getItem('money_moves_actor')||'Household'};try{billState=await api(editingId?`/api/bills/${editingId}`:'/api/bills',{method:editingId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});editingId=null;render();window.dispatchEvent(new Event('money-moves-bills-updated'))}catch(err){alert(err.message)}}}document.querySelectorAll('[data-bill-edit]').forEach(x=>x.onclick=()=>{editingId=Number(x.dataset.billEdit);render();setTimeout(()=>$('#billForm')?.scrollIntoView({behavior:'smooth',block:'center'}),50)});document.querySelectorAll('[data-bill-manual]').forEach(x=>x.onclick=async()=>{billState=await api(`/api/bills/${x.dataset.billManual}/manual`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paid:x.dataset.paid==='true',actor:localStorage.getItem('money_moves_actor')||'Household'})});render();window.dispatchEvent(new Event('money-moves-bills-updated'))});document.querySelectorAll('[data-bill-delete]').forEach(x=>x.onclick=async()=>{if(!confirm('Delete this planned bill?'))return;billState=await api(`/api/bills/${x.dataset.billDelete}`,{method:'DELETE'});render();window.dispatchEvent(new Event('money-moves-bills-updated'))})}
async function loadBills(){try{billState=await api('/api/bills');render()}catch(err){const h=$('#billPlanner');if(h)h.innerHTML=`<p class="error">${esc(err.message)}</p>`}}
function init(){const add=$('#addBillButton');if(add)add.onclick=()=>{editingId=0;render();setTimeout(()=>$('#billForm')?.scrollIntoView({behavior:'smooth',block:'center'}),50)};loadBills();window.addEventListener('money-moves-bills-updated',()=>{setTimeout(()=>location.reload(),250)},{once:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();