const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const {calculateDecisionPlan}=require('./src/engine');
const {config:plaidConfig,call:plaidCall,encryptToken,verifyWebhook}=require('./src/plaid');
const {syncHousehold,recomputeHouseholdState}=require('./src/bank');
const I=require('./src/insights');
let webpush=null;try{webpush=require('web-push')}catch{}
const PORT=Number(process.env.PORT||8080),ROOT=__dirname,DB_PATH=process.env.DB_PATH||path.join(ROOT,'data','money-moves.db'),TZ='America/New_York';
fs.mkdirSync(path.dirname(DB_PATH),{recursive:true});
const db=new DatabaseSync(DB_PATH);db.exec(`PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS households(id TEXT PRIMARY KEY,name TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS household_state(household_id TEXT PRIMARY KEY,checking REAL,reserve REAL,savings REAL,discretionary_spent REAL,updated_at TEXT);
CREATE TABLE IF NOT EXISTS rules(household_id TEXT PRIMARY KEY,checking_floor REAL,reserve_target REAL,discretionary_cap REAL,budget_eligible_va REAL,civilian_paycheck REAL,updated_at TEXT);
CREATE TABLE IF NOT EXISTS bank_items(item_id TEXT PRIMARY KEY,household_id TEXT,institution_id TEXT,institution_name TEXT,access_token_enc TEXT,cursor TEXT,status TEXT,sync_error TEXT,last_synced_at TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS bank_accounts(account_id TEXT PRIMARY KEY,item_id TEXT,household_id TEXT,name TEXT,official_name TEXT,mask TEXT,type TEXT,subtype TEXT,current_balance REAL,available_balance REAL,iso_currency_code TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS account_mappings(household_id TEXT,role TEXT,account_id TEXT,updated_at TEXT,PRIMARY KEY(household_id,role));
CREATE TABLE IF NOT EXISTS bank_transactions(transaction_id TEXT PRIMARY KEY,item_id TEXT,account_id TEXT,name TEXT,merchant_name TEXT,amount REAL,date TEXT,pending INTEGER,pfc_primary TEXT,pfc_detailed TEXT,raw_json TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS merchant_rules(merchant_key TEXT PRIMARY KEY,label TEXT,category TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS savings_routes(name TEXT PRIMARY KEY,percent REAL,sort_order INTEGER,updated_at TEXT);
CREATE TABLE IF NOT EXISTS activity(id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT,type TEXT,detail TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS push_subscriptions(endpoint TEXT PRIMARY KEY,subscription_json TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS checkpoints(month TEXT,checkpoint TEXT,completed_at TEXT,actor TEXT,PRIMARY KEY(month,checkpoint));
CREATE INDEX IF NOT EXISTS idx_bank_transactions_date ON bank_transactions(date);
CREATE INDEX IF NOT EXISTS idx_activity_created ON activity(created_at);
`);
const H='household_beta';
const BUDGET={spendableIncome:11659,monthlyExpenses:7991,operatingSurplus:3668,savingsBuffer:1089,totalSavingsTarget:4757,guaranteedIncome:7053,firstBills:4862.76,fifteenthBills:2552.10,anchorPayday:'2026-09-09'};
function now(){return new Date().toISOString()}
function seed(){if(!db.prepare('SELECT id FROM households WHERE id=?').get(H)){db.prepare('INSERT INTO households VALUES(?,?,?)').run(H,'Perez Household',now());db.prepare('INSERT INTO household_state VALUES(?,?,?,?,?,?)').run(H,2500.01,447.95,77273.21,0,now());db.prepare('INSERT INTO rules VALUES(?,?,?,?,?,?,?)').run(H,1000,2552.10,850,4158,2303,now());}if(!db.prepare('SELECT name FROM savings_routes LIMIT 1').get())db.prepare('INSERT INTO savings_routes VALUES(?,?,?,?)').run('Long-term savings',100,1,now());}
seed();
function json(res,c,d,headers={}){res.writeHead(c,{'Content-Type':'application/json','Cache-Control':'no-store',...headers});res.end(JSON.stringify(d))}
async function read(req){return await new Promise((ok,no)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}});req.on('error',no)})}
async function raw(req){return await new Promise((ok,no)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>ok(s));req.on('error',no)})}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));}
const ACCESS_KEY=process.env.MONEY_MOVES_ACCESS_KEY||'',SESSION_SECRET=process.env.SESSION_SECRET||process.env.BANK_TOKEN_ENCRYPTION_KEY||'money-moves-dev-session';
function sign(v){return crypto.createHmac('sha256',SESSION_SECRET).update(v).digest('base64url')}
function validSession(req){if(!ACCESS_KEY)return true;const token=cookies(req).mm_session;if(!token)return false;const [exp,sig]=token.split('.');if(!exp||!sig||Number(exp)<Date.now())return false;const expected=sign(exp);try{return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected))}catch{return false}}
function setSession(){const exp=String(Date.now()+30*86400000),token=`${exp}.${sign(exp)}`;return {'Set-Cookie':`mm_session=${encodeURIComponent(token)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`};}
function logActivity(type,detail,actor='Household'){db.prepare('INSERT INTO activity(actor,type,detail,created_at) VALUES(?,?,?,?)').run(actor,type,detail,now());}
function allTx(days=180){const d=new Date();d.setDate(d.getDate()-days);const since=d.toISOString().slice(0,10);return db.prepare(`SELECT bt.* FROM bank_transactions bt JOIN bank_accounts ba ON ba.account_id=bt.account_id WHERE ba.household_id=? AND bt.date>=? ORDER BY bt.date DESC`).all(H,since);}
function overrides(){return Object.fromEntries(db.prepare('SELECT merchant_key,category FROM merchant_rules').all().map(x=>[x.merchant_key,x.category]));}
function routes(){return db.prepare('SELECT name,percent,sort_order FROM savings_routes ORDER BY sort_order,name').all();}
function mappedAccount(role){return db.prepare(`SELECT a.* FROM account_mappings m JOIN bank_accounts a ON a.account_id=m.account_id WHERE m.household_id=? AND m.role=?`).get(H,role);}
function pushConfigured(){return !!(webpush&&process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT)}
if(pushConfigured())webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);
function buildState(){const s={...db.prepare('SELECT * FROM household_state WHERE household_id=?').get(H)},r=db.prepare('SELECT * FROM rules WHERE household_id=?').get(H),items=db.prepare('SELECT item_id,institution_name,status,sync_error,last_synced_at FROM bank_items WHERE household_id=?').all(H),accounts=db.prepare(`SELECT a.*,m.role FROM bank_accounts a LEFT JOIN account_mappings m ON m.account_id=a.account_id AND m.household_id=a.household_id WHERE a.household_id=?`).all(H),txs=allTx(),ov=overrides();const spend=I.spendSummary(txs,{cap:r.discretionary_cap,overrides:ov}),month=I.isoDate().slice(0,7),firstDone=!!db.prepare('SELECT completed_at FROM checkpoints WHERE month=? AND checkpoint=?').get(month,'first_bills'),operatingHoldback=firstDone?0:BUDGET.firstBills,plan=calculateDecisionPlan({checking:s.checking,reserve:s.reserve,savings:s.savings,checkingFloor:r.checking_floor,reserveTarget:r.reserve_target,civilianPaycheck:r.civilian_paycheck,operatingHoldback});s.discretionary_spent=spend.monthToDate.discretionary;const runway=I.billRunway({reserve:s.reserve,reserveTarget:r.reserve_target,checking:s.checking,checkingFloor:r.checking_floor,firstBills:BUDGET.firstBills,fifteenthBills:BUDGET.fifteenthBills}),incomeEvents=I.detectIncomeEvents(txs,{paycheck:r.civilian_paycheck,guaranteedIncome:BUDGET.guaranteedIncome}),subscriptions=I.detectSubscriptions(txs),alerts=I.unusualSpend(txs,{overrides:ov}),weekly=I.weeklyReport(txs,{overrides:ov}),savingAcct=mappedAccount('savings'),actualSaved=I.savingsActual(txs,savingAcct?.account_id),scorecard={target:BUDGET.totalSavingsTarget,actual:actualSaved,gap:I.round(BUDGET.totalSavingsTarget-actualSaved),operatingSurplus:BUDGET.operatingSurplus,savingsBuffer:BUDGET.savingsBuffer},forecast=I.cashflowForecast({checking:s.checking,reserve:s.reserve,paycheck:r.civilian_paycheck,guaranteedIncome:BUDGET.guaranteedIncome,firstBills:BUDGET.firstBills,fifteenthBills:BUDGET.fifteenthBills,anchorPayday:BUDGET.anchorPayday}),routing=I.savingsRouting(plan.toSavingsNow,routes()),brief=I.morningBrief({spend,runway,plan,alerts});return{state:s,rules:r,budget:BUDGET,plan,spend,brief,runway:{...runway,firstBillsConfirmed:firstDone},incomeEvents,subscriptions,alerts,weekly,scorecard,forecast,routing,savingsRoutes:routes(),activity:db.prepare('SELECT id,actor,type,detail,created_at FROM activity ORDER BY id DESC LIMIT 20').all(),merchantRules:db.prepare('SELECT merchant_key,label,category,updated_at FROM merchant_rules ORDER BY updated_at DESC LIMIT 50').all(),bank:{configured:plaidConfig().configured,environment:plaidConfig().env,items,accounts},security:{configured:!!ACCESS_KEY},push:{configured:pushConfigured()}};}
function staticFile(res,p){const map={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/styles.css':'styles.css','/oauth.html':'oauth.html','/sw.js':'sw.js','/manifest.webmanifest':'manifest.webmanifest','/icon-192.svg':'icon-192.svg','/icon-512.svg':'icon-512.svg'},f=map[p];if(!f)return false;const fp=path.join(ROOT,f);if(!fs.existsSync(fp))return false;const ext=path.extname(fp),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':ext==='.js'||ext==='.html'?'no-cache':'public, max-age=300'});fs.createReadStream(fp).pipe(res);return true}
async function sendPush(title,body,url='/'){if(!pushConfigured())return;const rows=db.prepare('SELECT endpoint,subscription_json FROM push_subscriptions').all();for(const row of rows){try{await webpush.sendNotification(JSON.parse(row.subscription_json),JSON.stringify({title,body,url}))}catch(e){if(e.statusCode===404||e.statusCode===410)db.prepare('DELETE FROM push_subscriptions WHERE endpoint=?').run(row.endpoint);else console.error('push',e.message)}}}
function metaGet(k){return db.prepare('SELECT value FROM app_meta WHERE key=?').get(k)?.value||null}
function metaSet(k,v){db.prepare(`INSERT INTO app_meta(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`).run(k,v,now())}
async function postSyncNotifications(before){const after=buildState();if(after.spend.discretionary.status==='hot'&&before?.spend?.discretionary?.status!=='hot')await sendPush('Money Moves: spending pace is hot',`You have used ${Math.round(after.spend.discretionary.spendProgress)}% of discretionary with ${Math.round(after.spend.discretionary.monthProgress)}% of the month elapsed.`);if(after.spend.discretionary.status==='over'&&before?.spend?.discretionary?.status!=='over')await sendPush('Money Moves: discretionary cap exceeded',`You have spent $${after.spend.monthToDate.discretionary.toFixed(2)} of the $${after.rules.discretionary_cap.toFixed(2)} monthly cap.`);if(after.alerts.length>before?.alerts?.length)await sendPush('Money Moves: unusual spend',`${after.alerts[0].merchant}: $${after.alerts[0].amount.toFixed(2)} looks unusual. Review it in Money Moves.`);if(after.incomeEvents.payday.detected&&!before?.incomeEvents?.payday?.detected)await sendPush('Payday Mode',`A $${after.incomeEvents.payday.amount.toFixed(2)} deposit landed. Open Money Moves for the exact routing plan.`);}
async function scheduler(){try{const p=I.isoDate(new Date(),TZ),parts=new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'short',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),obj=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));if(Number(obj.hour)===8&&metaGet('daily_brief')!==p){const s=buildState();await sendPush('Morning Money Brief',s.brief);metaSet('daily_brief',p)}if(obj.weekday==='Sat'&&Number(obj.hour)===8&&metaGet('weekly_brief')!==p){const s=buildState();await sendPush('Weekly Money Moves',`Last 7 days: $${s.weekly.spent.toFixed(2)} spent, $${s.weekly.discretionary.toFixed(2)} discretionary, $${s.weekly.income.toFixed(2)} income. Savings target progress: $${s.scorecard.actual.toFixed(2)} / $${s.scorecard.target.toFixed(2)}.`);metaSet('weekly_brief',p)}}catch(e){console.error('scheduler',e)}}
setInterval(scheduler,10*60*1000).unref();setTimeout(scheduler,5000).unref();
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');
if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,version:'0.5.0',bankConfigured:plaidConfig().configured,pushConfigured:pushConfigured(),accessProtected:!!ACCESS_KEY});
if(req.method==='GET'&&u.pathname==='/api/auth-status')return json(res,200,{required:!!ACCESS_KEY,authenticated:validSession(req)});
if(req.method==='POST'&&u.pathname==='/api/login'){if(!ACCESS_KEY)return json(res,200,{ok:true});const b=await read(req),a=Buffer.from(String(b.key||'')),c=Buffer.from(ACCESS_KEY);if(a.length!==c.length||!crypto.timingSafeEqual(a,c))return json(res,401,{error:'Invalid household access key'});return json(res,200,{ok:true},setSession());}
if(req.method==='POST'&&u.pathname==='/api/plaid/webhook'){const text=await raw(req);if(!(await verifyWebhook(text,req.headers['plaid-verification'])))return json(res,401,{error:'Invalid webhook signature'});const b=JSON.parse(text||'{}'),item=db.prepare('SELECT * FROM bank_items WHERE item_id=?').get(b.item_id||'');if(item&&b.webhook_type==='TRANSACTIONS'&&b.webhook_code==='SYNC_UPDATES_AVAILABLE'){const before=buildState();syncHousehold(db,H).then(()=>postSyncNotifications(before)).catch(console.error)}return json(res,200,{received:true});}
if(u.pathname.startsWith('/api/')&&!validSession(req))return json(res,401,{error:'Household access key required'});
if(req.method==='GET'&&u.pathname==='/api/state')return json(res,200,buildState());
if(req.method==='GET'&&u.pathname==='/api/push/public-key')return json(res,200,{configured:pushConfigured(),publicKey:pushConfigured()?process.env.VAPID_PUBLIC_KEY:null});
if(req.method==='POST'&&u.pathname==='/api/push/subscribe'){if(!pushConfigured())return json(res,503,{error:'Push is not configured'});const b=await read(req);if(!b.endpoint)return json(res,400,{error:'Invalid push subscription'});db.prepare(`INSERT INTO push_subscriptions(endpoint,subscription_json,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET subscription_json=excluded.subscription_json,updated_at=excluded.updated_at`).run(b.endpoint,JSON.stringify(b),now(),now());logActivity('push_enabled','Push alerts enabled');return json(res,201,{ok:true});}
if(req.method==='POST'&&u.pathname==='/api/bank/link-token'){const cfg=plaidConfig();if(!cfg.configured)return json(res,503,{error:'Plaid is not configured'});const q={user:{client_user_id:H},client_name:'Money Moves',products:['transactions'],country_codes:['US'],language:'en',transactions:{days_requested:730}};if(cfg.webhook)q.webhook=cfg.webhook;if(cfg.redirectUri)q.redirect_uri=cfg.redirectUri;const x=await plaidCall('/link/token/create',q);return json(res,200,{linkToken:x.link_token,expiration:x.expiration});}
if(req.method==='POST'&&u.pathname==='/api/bank/exchange'){const b=await read(req);if(!b.publicToken)return json(res,400,{error:'Missing public token'});const x=await plaidCall('/item/public_token/exchange',{public_token:b.publicToken});let name='Connected bank',iid=null;try{const item=await plaidCall('/item/get',{access_token:x.access_token});iid=item.item?.institution_id||null;if(iid){const inst=await plaidCall('/institutions/get_by_id',{institution_id:iid,country_codes:['US']});name=inst.institution?.name||name}}catch{}const t=now();db.prepare(`INSERT INTO bank_items(item_id,household_id,institution_id,institution_name,access_token_enc,cursor,status,sync_error,last_synced_at,created_at,updated_at) VALUES(?,?,?,?,?,NULL,'active',NULL,NULL,?,?) ON CONFLICT(item_id) DO UPDATE SET access_token_enc=excluded.access_token_enc,institution_name=excluded.institution_name,updated_at=excluded.updated_at`).run(x.item_id,H,iid,name,encryptToken(x.access_token),t,t);await syncHousehold(db,H);logActivity('bank_connected',`${name} connected`);return json(res,201,{ok:true,state:buildState()});}
if(req.method==='POST'&&u.pathname==='/api/bank/sync'){const before=buildState(),result=await syncHousehold(db,H,{refresh:true});logActivity('bank_sync','Bank data refreshed');await postSyncNotifications(before);return json(res,200,{ok:true,result,state:buildState()});}
if(req.method==='PATCH'&&u.pathname==='/api/bank/mappings'){const b=await read(req),t=now();for(const role of ['checking','reserve','savings'])if(b[role])db.prepare(`INSERT INTO account_mappings VALUES(?,?,?,?) ON CONFLICT(household_id,role) DO UPDATE SET account_id=excluded.account_id,updated_at=excluded.updated_at`).run(H,role,b[role],t);recomputeHouseholdState(db,H);logActivity('account_mapping','Bank account mapping updated',b.actor||'Household');return json(res,200,buildState());}
if(req.method==='PATCH'&&u.pathname==='/api/merchant-rule'){const b=await read(req),allowed=['discretionary','groceries','gas','essential','ignore'];if(!allowed.includes(b.category))return json(res,400,{error:'Invalid category'});const t=db.prepare('SELECT * FROM bank_transactions WHERE transaction_id=?').get(b.transactionId);if(!t)return json(res,404,{error:'Transaction not found'});const label=I.merchant(t),key=I.norm(label);db.prepare(`INSERT INTO merchant_rules(merchant_key,label,category,updated_at) VALUES(?,?,?,?) ON CONFLICT(merchant_key) DO UPDATE SET label=excluded.label,category=excluded.category,updated_at=excluded.updated_at`).run(key,label,b.category,now());logActivity('merchant_rule',`${label} → ${b.category}`,b.actor||'Household');return json(res,200,buildState());}
if(req.method==='PUT'&&u.pathname==='/api/savings-routes'){const b=await read(req),list=Array.isArray(b.routes)?b.routes:[],total=list.reduce((s,x)=>s+Number(x.percent||0),0);if(!list.length||Math.abs(total-100)>.01)return json(res,400,{error:'Savings route percentages must total 100%'});db.exec('BEGIN');try{db.prepare('DELETE FROM savings_routes').run();list.forEach((x,i)=>db.prepare('INSERT INTO savings_routes VALUES(?,?,?,?)').run(String(x.name||`Goal ${i+1}`).slice(0,80),Number(x.percent||0),i+1,now()));db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}logActivity('savings_routes','Savings routing updated',b.actor||'Household');return json(res,200,buildState());}
if(req.method==='POST'&&u.pathname==='/api/checkpoint'){const b=await read(req),month=I.isoDate().slice(0,7),checkpoint=String(b.checkpoint||'');if(!['first_bills'].includes(checkpoint))return json(res,400,{error:'Invalid checkpoint'});if(b.completed===false)db.prepare('DELETE FROM checkpoints WHERE month=? AND checkpoint=?').run(month,checkpoint);else db.prepare(`INSERT INTO checkpoints(month,checkpoint,completed_at,actor) VALUES(?,?,?,?) ON CONFLICT(month,checkpoint) DO UPDATE SET completed_at=excluded.completed_at,actor=excluded.actor`).run(month,checkpoint,now(),String(b.actor||'Household').slice(0,60));logActivity('checkpoint',b.completed===false?'1st-of-month bills marked unconfirmed':'1st-of-month bills marked paid',b.actor||'Household');return json(res,200,buildState());}
if(req.method==='POST'&&u.pathname==='/api/activity'){const b=await read(req);logActivity(String(b.type||'note').slice(0,40),String(b.detail||'').slice(0,240),String(b.actor||'Household').slice(0,60));return json(res,201,{ok:true,activity:buildState().activity});}
if(staticFile(res,u.pathname))return;json(res,404,{error:'Not found'});
}catch(e){console.error(e);json(res,500,{error:e.message||'Server error'})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`Money Moves v0.5 listening on ${PORT}`));
