function round(n){return Math.round((Number(n)||0)*100)/100;}
function median(nums){const a=nums.slice().sort((x,y)=>x-y);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ');}
function merchant(t){return t.merchant_name||t.name||'Transaction';}
function rawTransaction(t){try{return JSON.parse(t.raw_json||'{}')}catch{return{}}}
function branding(t){const raw=rawTransaction(t);return{logoUrl:raw.logo_url||raw.merchant_logo_url||null,website:raw.website||raw.merchant_website||null};}
function localParts(date=new Date(),tz='America/New_York'){const parts=new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));}
function isoDate(date=new Date(),tz='America/New_York'){const p=localParts(date,tz);return `${p.year}-${p.month}-${p.day}`;}
function daysInMonth(y,m){return new Date(Number(y),Number(m),0).getDate();}
function isTransfer(t){const p=String(t.pfc_primary||'').toUpperCase(),d=String(t.pfc_detailed||'').toUpperCase();return p.startsWith('TRANSFER_')||p==='LOAN_PAYMENTS'||d.includes('CREDIT_CARD_PAYMENT');}
function isSpend(t){return Number(t.amount||0)>0&&!t.pending&&!isTransfer(t);}
function isIncome(t){return Number(t.amount||0)<0&&!t.pending&&!isTransfer(t);}
function classify(t,override){if(override)return override;const amount=Number(t.amount||0),text=norm(`${t.merchant_name||''} ${t.name||''}`),primary=String(t.pfc_primary||'').toUpperCase(),detailed=String(t.pfc_detailed||'').toUpperCase();if(amount<=0||t.pending)return 'ignore';if(text.includes('walmart'))return 'groceries';if(text.includes('7-eleven')||text.includes('7-11'))return amount<=30?'discretionary':'gas';if(text.includes('amazon'))return 'discretionary';if(text.includes('jba-andrews main')||text.includes('jba andrews main'))return 'discretionary';if(primary==='ENTERTAINMENT'||primary==='FOOD_AND_DRINK')return 'discretionary';if(/BARBER|HAIR|SALON|NAIL|SPA/.test(detailed)||/barber|hair|salon|nail|spa/.test(text))return 'discretionary';if(primary.includes('GROCER'))return 'groceries';if(primary.includes('TRANSPORTATION')||detailed.includes('GAS'))return 'gas';if(primary.includes('RENT')||primary.includes('UTILITIES'))return 'utilities';return 'essential';}
function spendSummary(txs,{today=isoDate(),cap=850,overrides={}}={}){const [y,m,d]=today.split('-').map(Number),days=daysInMonth(y,m),elapsed=Math.max(1,d),month=today.slice(0,7);const yesterdayDate=new Date(`${today}T12:00:00Z`);yesterdayDate.setUTCDate(yesterdayDate.getUTCDate()-1);const yesterday=yesterdayDate.toISOString().slice(0,10);const monthTx=txs.filter(t=>String(t.date||'').startsWith(month));const mapped=monthTx.map(t=>({...t,_class:classify(t,overrides[norm(merchant(t))])}));const spend=mapped.filter(isSpend),disc=spend.filter(t=>t._class==='discretionary');const sum=rows=>round(rows.reduce((s,t)=>s+Number(t.amount||0),0));const discSpent=sum(disc),remaining=round(Math.max(0,cap-discSpent)),monthProgress=round(elapsed/days*100),spendProgress=cap?round(discSpent/cap*100):0;const paceDelta=round(spendProgress-monthProgress),dailyAllowance=round(remaining/Math.max(1,days-elapsed+1));const top=spend.slice().sort((a,b)=>Number(b.amount)-Number(a.amount)).slice(0,8).map(t=>({id:t.transaction_id,merchant:merchant(t),amount:round(t.amount),date:t.date,category:t._class,plaidCategory:t.pfc_primary||'OTHER',...branding(t)}));return{today:{date:today,total:sum(spend.filter(t=>t.date===today)),discretionary:sum(disc.filter(t=>t.date===today))},yesterday:{date:yesterday,total:sum(spend.filter(t=>t.date===yesterday)),discretionary:sum(disc.filter(t=>t.date===yesterday))},monthToDate:{month,total:sum(spend),discretionary:discSpent,transactionCount:spend.length},discretionary:{cap:round(cap),remaining,monthProgress,spendProgress,paceDelta,dailyAllowance,status:discSpent>cap?'over':paceDelta>12?'hot':paceDelta<-10?'good':'on_track'},topTransactions:top};}
function detectSubscriptions(txs){const groups=new Map();for(const t of txs){if(!isSpend(t)||isTransfer(t))continue;const key=norm(merchant(t));if(!key)continue;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(t);}const out=[];for(const [key,rows] of groups){if(rows.length<2)continue;rows.sort((a,b)=>String(a.date).localeCompare(String(b.date)));const amounts=rows.map(x=>Number(x.amount||0));const med=median(amounts);if(med<4)continue;const stable=amounts.filter(a=>Math.abs(a-med)<=Math.max(2,med*.15)).length/amounts.length;if(stable<.65)continue;const gaps=[];for(let i=1;i<rows.length;i++)gaps.push((Date.parse(rows[i].date+'T00:00:00Z')-Date.parse(rows[i-1].date+'T00:00:00Z'))/86400000);const gap=median(gaps);if(gap<20||gap>40)continue;const last=rows[rows.length-1],prior=rows.slice(0,-1),priorMed=prior.length?median(prior.map(x=>Number(x.amount||0))):med,lastAmount=Number(last.amount||0),priceChange=priorMed&&Math.abs(lastAmount-priorMed)>=Math.max(1,priorMed*.08)?round(lastAmount-priorMed):0;const next=new Date(last.date+'T12:00:00Z');next.setUTCDate(next.getUTCDate()+Math.round(gap));out.push({merchant:merchant(last),amount:round(lastAmount),typicalAmount:round(med),priceChange,frequencyDays:Math.round(gap),lastDate:last.date,nextExpected:next.toISOString().slice(0,10),occurrences:rows.length,...branding(last)});}return out.sort((a,b)=>b.amount-a.amount).slice(0,12);}
function unusualSpend(txs,{today=isoDate(),overrides={}}={}){const month=today.slice(0,7),spend=txs.filter(t=>isSpend(t)&&String(t.date||'').startsWith(month));const amounts=spend.map(t=>Number(t.amount||0)).filter(a=>a>0);const med=Math.max(1,median(amounts));return spend.filter(t=>Number(t.amount)>=Math.max(200,med*3)).map(t=>({id:t.transaction_id,merchant:merchant(t),amount:round(t.amount),date:t.date,category:classify(t,overrides[norm(merchant(t))]),reason:`${round(Number(t.amount)/med)}x typical transaction`,...branding(t)})).sort((a,b)=>b.amount-a.amount).slice(0,8);}
function detectIncomeEvents(txs,{paycheck=2303,guaranteedIncome=7053,today=isoDate()}={}){const recentDate=new Date(`${today}T12:00:00Z`);recentDate.setUTCDate(recentDate.getUTCDate()-4);const since=recentDate.toISOString().slice(0,10);const inflows=txs.filter(t=>isIncome(t)&&t.date>=since).map(t=>({...t,inflow:Math.abs(Number(t.amount||0))}));const paycheckHit=inflows.find(t=>Math.abs(t.inflow-paycheck)<=Math.max(75,paycheck*.08));const firstHits=inflows.filter(t=>Number(String(t.date).slice(-2))<=3),firstTotal=round(firstHits.reduce((s,t)=>s+t.inflow,0));return{payday:paycheckHit?{detected:true,date:paycheckHit.date,amount:round(paycheckHit.inflow),merchant:merchant(paycheckHit)}:{detected:false},firstOfMonth:firstTotal>=guaranteedIncome*.85?{detected:true,total:firstTotal,transactions:firstHits.length}:{detected:false,total:firstTotal}};}
function billRunway({today=isoDate(),reserve=0,reserveTarget=2552.10,checking=0,checkingFloor=1000,firstBills=4862.76,fifteenthBills=2552.10}){const day=Number(today.slice(-2));const reserveGap=round(Math.max(0,reserveTarget-reserve)),floorGap=round(Math.max(0,checkingFloor-checking));let checkpoint,nextDue,required,funded,status;if(day<=15){checkpoint='15th bills';nextDue=`${today.slice(0,8)}15`;required=fifteenthBills;funded=Math.min(reserve,reserveTarget);status=reserveGap<=0?'funded':'needs_funding';}else{const [y,m]=today.split('-').map(Number);const next=new Date(Date.UTC(y,m,1));nextDue=next.toISOString().slice(0,10);checkpoint='1st-of-month bills';required=firstBills;funded=Math.max(0,checking-checkingFloor);status=funded>=required?'funded':'watch';}return{checkpoint,nextDue,required:round(required),funded:round(funded),gap:day<=15?reserveGap:round(Math.max(0,required-funded)),checkingFloor:round(checkingFloor),floorGap,status};}
function savingsActual(txs,savingsAccountId,today=isoDate()){if(!savingsAccountId)return 0;const month=today.slice(0,7);return round(txs.filter(t=>t.account_id===savingsAccountId&&!t.pending&&String(t.date||'').startsWith(month)&&Number(t.amount||0)<0).reduce((s,t)=>s+Math.abs(Number(t.amount||0)),0));}
function weeklyReport(txs,{today=isoDate(),overrides={}}={}){const end=new Date(`${today}T12:00:00Z`),start=new Date(end);start.setUTCDate(start.getUTCDate()-6);const since=start.toISOString().slice(0,10),rows=txs.filter(t=>t.date>=since&&t.date<=today&&!t.pending),spend=rows.filter(isSpend),income=rows.filter(isIncome);const sum=r=>round(r.reduce((s,t)=>s+Math.abs(Number(t.amount||0)),0));return{from:since,to:today,spent:sum(spend),discretionary:sum(spend.filter(t=>classify(t,overrides[norm(merchant(t))])==='discretionary')),income:sum(income),transactions:spend.length};}
function cashflowForecast({today=isoDate(),checking=0,reserve=0,paycheck=2303,guaranteedIncome=7053,firstBills=4862.76,fifteenthBills=2552.10,anchorPayday='2026-09-09',days=30}){const start=new Date(`${today}T12:00:00Z`),end=new Date(start);end.setUTCDate(end.getUTCDate()+days);const events=[];const push=(date,type,label,amount)=>{if(date>=start&&date<=end)events.push({date:date.toISOString().slice(0,10),type,label,amount:round(amount)});};let p=new Date(`${anchorPayday}T12:00:00Z`);while(p<start)p.setUTCDate(p.getUTCDate()+14);while(p<=end){push(new Date(p),'income','Civilian paycheck',paycheck);p.setUTCDate(p.getUTCDate()+14);}let cursor=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth(),1,12));for(let i=0;i<3;i++){const first=new Date(cursor);push(first,'income','VA + Coast Guard',guaranteedIncome);push(first,'bill','1st bills',-firstBills);const fifteenth=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth(),15,12));push(fifteenth,'bill','15th bills',-fifteenthBills);cursor=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth()+1,1,12));}events.sort((a,b)=>a.date.localeCompare(b.date)||(b.amount-a.amount));let projected=round(checking+reserve);for(const e of events){projected=round(projected+e.amount);e.projectedLiquid=projected;}return{startingLiquid:round(checking+reserve),through:end.toISOString().slice(0,10),events};}
function morningBrief({spend,runway,plan,alerts=[]}){const bits=[];bits.push(`Yesterday you spent $${spend.yesterday.total.toFixed(2)}; $${spend.yesterday.discretionary.toFixed(2)} was discretionary.`);bits.push(`You have $${spend.discretionary.remaining.toFixed(2)} left in discretionary, about $${spend.discretionary.dailyAllowance.toFixed(2)}/day for the rest of the month.`);bits.push(runway.status==='funded'?`${runway.checkpoint} is funded.`:`${runway.checkpoint} has a $${runway.gap.toFixed(2)} funding gap.`);bits.push(`Safe-to-spend right now: $${plan.safeToSpendNow.toFixed(2)}.`);if(alerts.length)bits.push(`${alerts.length} unusual transaction${alerts.length===1?'':'s'} need a look.`);return bits.join(' ');}
function savingsRouting(amount,routes){const active=(routes||[]).filter(r=>Number(r.percent)>0),total=active.reduce((s,r)=>s+Number(r.percent),0)||100;let allocated=0;return active.map((r,i)=>{const value=i===active.length-1?round(amount-allocated):round(amount*Number(r.percent)/total);allocated=round(allocated+value);return{name:r.name,percent:Number(r.percent),amount:value};});}
module.exports={round,norm,merchant,branding,isoDate,isSpend,isIncome,isTransfer,classify,spendSummary,detectSubscriptions,unusualSpend,detectIncomeEvents,billRunway,savingsActual,weeklyReport,cashflowForecast,morningBrief,savingsRouting};