const crypto=require('node:crypto');
const ENV_URLS={sandbox:'https://sandbox.plaid.com',production:'https://production.plaid.com'};
function config(){const env=process.env.PLAID_ENV||'sandbox';return{env,baseUrl:ENV_URLS[env]||ENV_URLS.sandbox,clientId:process.env.PLAID_CLIENT_ID||'',secret:process.env.PLAID_SECRET||'',redirectUri:process.env.PLAID_REDIRECT_URI||undefined,webhook:process.env.PLAID_WEBHOOK_URL||undefined,configured:!!(process.env.PLAID_CLIENT_ID&&process.env.PLAID_SECRET)};}
async function call(endpoint,payload={}){const cfg=config();if(!cfg.configured)throw new Error('Plaid is not configured');const r=await fetch(`${cfg.baseUrl}${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json','PLAID-CLIENT-ID':cfg.clientId,'PLAID-SECRET':cfg.secret,'Plaid-Version':'2020-09-14'},body:JSON.stringify(payload)}),data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.error_message||data.error_code||`Plaid request failed (${r.status})`);e.code=data.error_code;e.type=data.error_type;e.requestId=data.request_id;throw e;}return data;}
function encryptionKey(){const raw=process.env.BANK_TOKEN_ENCRYPTION_KEY||'';if(!raw)throw new Error('BANK_TOKEN_ENCRYPTION_KEY is not configured');if(/^[a-f0-9]{64}$/i.test(raw))return Buffer.from(raw,'hex');try{const b=Buffer.from(raw,'base64');if(b.length===32)return b;}catch{}return crypto.createHash('sha256').update(raw).digest();}
function encryptToken(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',encryptionKey(),iv),encrypted=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]),tag=cipher.getAuthTag();return Buffer.concat([iv,tag,encrypted]).toString('base64url');}
function decryptToken(blob){const buf=Buffer.from(blob,'base64url'),iv=buf.subarray(0,12),tag=buf.subarray(12,28),encrypted=buf.subarray(28),decipher=crypto.createDecipheriv('aes-256-gcm',encryptionKey(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(encrypted),decipher.final()]).toString('utf8');}
const keyCache=new Map();function decodeB64Json(part){return JSON.parse(Buffer.from(part,'base64url').toString('utf8'));}
async function verifyWebhook(rawBody,signedJwt){if(!signedJwt)return false;const parts=String(signedJwt).split('.');if(parts.length!==3)return false;let header,payload;try{header=decodeB64Json(parts[0]);payload=decodeB64Json(parts[1]);}catch{return false;}if(header.alg!=='ES256'||!header.kid)return false;const nowSeconds=Math.floor(Date.now()/1000);if(!Number.isFinite(payload.iat)||Math.abs(nowSeconds-payload.iat)>300)return false;let jwk=keyCache.get(header.kid);if(!jwk){try{jwk=(await call('/webhook_verification_key/get',{key_id:header.kid})).key;keyCache.set(header.kid,jwk);}catch{return false;}}try{const publicKey=crypto.createPublicKey({key:jwk,format:'jwk'}),signingInput=Buffer.from(`${parts[0]}.${parts[1]}`),signature=Buffer.from(parts[2],'base64url'),validSig=crypto.verify('sha256',signingInput,{key:publicKey,dsaEncoding:'ieee-p1363'},signature);if(!validSig)return false;const actual=crypto.createHash('sha256').update(rawBody).digest('hex'),claimed=String(payload.request_body_sha256||'');if(claimed.length!==actual.length)return false;return crypto.timingSafeEqual(Buffer.from(actual),Buffer.from(claimed));}catch{return false;}}
module.exports={config,call,encryptToken,decryptToken,verifyWebhook};
